import { PLAYER_ANIMATION_STATES } from "../ids";
import type { PlayerAnimationState, PlayerSheet } from "../../types/assets";

export const PLAYER_SHEETS: Record<PlayerAnimationState, PlayerSheet> = {
  [PLAYER_ANIMATION_STATES.idle]: {
    src: "assets/sprites/player/player_idle.png",
    frameW: 384,
    frameH: 480,
    count: 8,
    image: null,
    drawW: 96,
    drawH: 120,
    animSpeed: 8,
    anchorY: 0.979,
  },
  [PLAYER_ANIMATION_STATES.run]: {
    src: "assets/sprites/player/player_run.png",
    frameW: 448,
    frameH: 420,
    count: 8,
    image: null,
    drawW: 120,
    drawH: 112,
    animSpeed: 4,
    anchorY: 0.976,
  },
  [PLAYER_ANIMATION_STATES.jump]: {
    src: "assets/sprites/player/player_jump.png",
    frameW: 448,
    frameH: 420,
    count: 6,
    image: null,
    drawW: 124,
    drawH: 116,
    animSpeed: 7,
    anchorY: 0.971,
  },
  [PLAYER_ANIMATION_STATES.attack]: {
    src: "assets/sprites/player/player_attack.png",
    frameW: 768,
    frameH: 480,
    count: 8,
    image: null,
    drawW: 227,
    drawH: 142,
    animSpeed: 3,
    anchorY: 0.979,
  },
  [PLAYER_ANIMATION_STATES.fallAttack]: {
    src: "assets/sprites/player/player_fall_attack.png",
    frameW: 640,
    frameH: 560,
    count: 8,
    image: null,
    drawW: 178,
    drawH: 156,
    animSpeed: 4,
    anchorY: 0.982,
  },
};
