import { SKILL_IDS } from "../ids";
import type { Skill } from "../../types/assets";

export const SKILLS: Skill[] = [
  {
    id: SKILL_IDS.lineProjectile,
    name: "潮龙·破阵",
    description: "抬刃聚潮后向前释放潮龙，造成窄长路径伤害，用于直线远程点杀。",
    typeTag: "line_projectile",
    implemented: true,
    iconSrc: "assets/sprites/skills/line_projectile/icon.png",
    levelDescriptions: {
      1: "向前释放潮龙，攻击力 x1.2，形成基础窄长路径。",
      2: "潮龙伤害 +18%，路径宽高约 +7%。",
      3: "潮龙伤害 +35%，路径宽高约 +14%。",
    },
    src: "assets/sprites/skills/line_projectile/skill.png",
    frameCount: 5,
    frameW: 800,
    image: null,
    frameH: 420,
    drawScale: 0.247,
    anchorX: 0.15,
    radius: 30,
    enemyBase: 34,
    enemyScale: 42,
    bossBase: 56,
    color: "#7fdfff",
  },
  {
    id: SKILL_IDS.closeArc,
    name: "弦月·潮刃",
    description: "挥刃打出前方月牙潮刃，用短距离宽判定处理近身包围。",
    typeTag: "close_arc",
    implemented: true,
    iconSrc: "assets/sprites/skills/close_arc/icon.png",
    levelDescriptions: {
      1: "前方月牙潮刃，攻击力 x1.5，最大飞行 140px。",
      2: "潮刃伤害 +18%，最大飞行 158px，判定宽高约 +6%。",
      3: "潮刃伤害 +35%，最大飞行 176px，判定宽高约 +12%。",
    },
    src: "assets/sprites/skills/close_arc/skill.png",
    frameCount: 6,
    frameW: 500,
    image: null,
    frameH: 500,
    drawScale: 0.243,
    radius: 30,
    enemyBase: 37,
    enemyScale: 45,
    bossBase: 62,
    color: "#8edbff",
  },
  {
    id: SKILL_IDS.guardCounter,
    name: "镜潮·护返",
    description: "短暂起手后展开环身潮幕，预判受击时抵挡并反击近处目标。",
    typeTag: "guard_counter",
    implemented: true,
    iconSrc: "assets/sprites/skills/guard_counter/icon.png",
    levelDescriptions: {
      1: "潮幕成形后进入 72 帧防护窗口，最多抵挡并反击 3 次。",
      2: "反击伤害 +18%，防护窗口 78 帧，反击判定外扩 6px。",
      3: "反击伤害 +35%，防护窗口 84 帧，最多反击 4 次，判定外扩 10px。",
    },
    src: "assets/sprites/skills/guard_counter/skill.png",
    frameCount: 5,
    frameW: 540,
    image: null,
    frameH: 470,
    drawScale: 0.256,
    radius: 30,
    enemyBase: 40,
    enemyScale: 48,
    bossBase: 68,
    color: "#9be6ff",
  },
  {
    id: SKILL_IDS.dashReposition,
    name: "流步·潮闪",
    description: "踏步后短距离踏浪闪进，穿击身前敌人并以收刀斩结束。",
    typeTag: "dash_reposition",
    implemented: true,
    iconSrc: "assets/sprites/skills/dash_reposition/icon.png",
    levelDescriptions: {
      1: "短位移 92px，穿击和收刀斩伤害 x1.1。",
      2: "位移 108px，收刀判定 96x54，伤害 x1.25。",
      3: "位移 124px，收刀判定 110x56，伤害 x1.4。",
    },
    src: "assets/sprites/skills/dash_reposition/skill.png",
    frameCount: 5,
    frameW: 480,
    image: null,
    frameH: 360,
    drawScale: 0.42,
    anchorX: 0.45,
    anchorY: 0.9,
    radius: 96,
    enemyBase: 28,
    enemyScale: 36,
    bossBase: 38,
    color: "#7bdcff",
  },
  {
    id: SKILL_IDS.vortexControl,
    name: "回涡·引潮",
    description: "插刃引出短时地面潮涡，轻微牵引并减速轻型敌人。",
    typeTag: "vortex_control",
    implemented: true,
    iconSrc: "assets/sprites/skills/vortex_control/icon.png",
    levelDescriptions: {
      1: "潮涡持续 54 帧，半径 82px，牵引 0.85，减速 0.86，伤害 x0.36。",
      2: "持续 66 帧，半径 92px，牵引 1.05，减速 0.80，伤害 x0.42。",
      3: "持续 78 帧，半径 102px，牵引 1.25，减速 0.74，伤害 x0.48，但仍不拉动 Boss。",
    },
    src: "assets/sprites/skills/vortex_control/skill.png",
    frameCount: 5,
    frameW: 360,
    image: null,
    frameH: 360,
    drawScale: 0.34,
    anchorX: 0.52,
    radius: 92,
    enemyBase: 18,
    enemyScale: 26,
    bossBase: 24,
    color: "#65d6ff",
  },
  {
    id: SKILL_IDS.armorBreak,
    name: "断浪·裂甲",
    description: "压缩潮线向前飞行，命中后爆裂并施加短时裂甲标记。",
    typeTag: "armor_break",
    implemented: true,
    iconSrc: "assets/sprites/skills/armor_break/icon.png",
    levelDescriptions: {
      1: "潮线飞行 118px，伤害 x1.25，裂甲 180 帧，后续伤害 x1.18。",
      2: "飞行 132px，伤害 x1.42，裂甲 210 帧，后续伤害 x1.24。",
      3: "飞行 146px，伤害 x1.6，裂甲 240 帧，后续伤害 x1.3，Boss 缩放较低。",
    },
    src: "assets/sprites/skills/armor_break/skill.png",
    frameCount: 5,
    frameW: 360,
    image: null,
    frameH: 360,
    drawScale: 0.34,
    anchorX: 0.46,
    radius: 128,
    enemyBase: 34,
    enemyScale: 42,
    bossBase: 48,
    color: "#b7efff",
  },
  {
    id: SKILL_IDS.antiAirMulti,
    name: "雨线·穿针",
    description: "抬手定线后召来多条细潮线斜落，用于对空和远程骚扰。",
    typeTag: "anti_air_multi",
    implemented: true,
    iconSrc: "assets/sprites/skills/anti_air_multi/icon.png",
    levelDescriptions: {
      1: "落下 4 条潮线，单段伤害 x0.56，判定高度 142px。",
      2: "落下 5 条潮线，单段伤害 x0.62，判定高度 150px。",
      3: "落下 6 条潮线，单段伤害 x0.68，判定高度 158px。",
    },
    src: "assets/sprites/skills/anti_air_multi/skill.png",
    frameCount: 5,
    frameW: 640,
    image: null,
    frameH: 420,
    drawScale: 0.5,
    anchorX: 0.45,
    anchorY: 0.93,
    radius: 150,
    enemyBase: 18,
    enemyScale: 24,
    bossBase: 26,
    color: "#9eeaff",
  },
  {
    id: SKILL_IDS.returningBlade,
    name: "回刃·归潮",
    description: "放出潮刃后沿路径回收，去程和返程分别可命中。",
    typeTag: "returning_blade",
    implemented: true,
    iconSrc: "assets/sprites/skills/returning_blade/icon.png",
    levelDescriptions: {
      1: "潮刃飞行 170px 后返回，最多 2 次命中，伤害 x0.9。",
      2: "飞行 195px 后返回，最多 3 次命中，伤害 x1.05。",
      3: "飞行 220px 后返回，最多 4 次命中，伤害 x1.2，但不自动追踪全场。",
    },
    src: "assets/sprites/skills/returning_blade/skill.png",
    frameCount: 5,
    frameW: 360,
    image: null,
    frameH: 360,
    drawScale: 0.58,
    anchorX: 0.48,
    radius: 150,
    enemyBase: 25,
    enemyScale: 34,
    bossBase: 42,
    color: "#80e2ff",
  },
  {
    id: SKILL_IDS.verticalWave,
    name: "升浪·托月",
    description: "压低重心后升起短浪柱，处理纵向目标和平台边缘贴身压力。",
    typeTag: "vertical_wave",
    implemented: true,
    iconSrc: "assets/sprites/skills/vertical_wave/icon.png",
    levelDescriptions: {
      1: "升起 72x130 浪柱，伤害 x1.15，击退上托 8px。",
      2: "浪柱 82x145，伤害 x1.3，击退上托 10px。",
      3: "浪柱 92x160，伤害 x1.45，击退上托 12px，但不长期浮空连控。",
    },
    src: "assets/sprites/skills/vertical_wave/skill.png",
    frameCount: 6,
    frameW: 480,
    image: null,
    frameH: 420,
    drawScale: 0.34,
    anchorX: 0.4,
    anchorY: 0.98,
    radius: 110,
    enemyBase: 30,
    enemyScale: 38,
    bossBase: 44,
    color: "#9be8ff",
  },
];
