import { SKILL_IDS } from "../ids";
import type { Skill } from "../../types/assets";

export const SKILLS: Skill[] = [
  {
    id: SKILL_IDS.lineProjectile,
    name: "潮龙·破阵",
    description: "抬刃聚潮后向前释放潮龙，造成窄长路径伤害，用于直线远程点杀。",
    typeTag: "line_projectile",
    implemented: true,
    iconSrc: "assets/sprites/skills/line_projectile/icon.png",
    levelDescriptions: {
      1: "向前释放潮龙，造成窄长路径伤害。",
      2: "潮龙伤害提升，路径命中反馈更稳定。",
      3: "潮龙伤害进一步提升，直线压制更可靠。",
    },
    src: "assets/sprites/skills/line_projectile/skill.png",
    frameCount: 5,
    frameW: 800,
    image: null,
    frameH: 420,
    drawScale: 0.247,
    anchorX: 0.15,
    radius: 30,
    enemyBase: 34,
    enemyScale: 42,
    bossBase: 56,
    color: "#7fdfff",
  },
  {
    id: SKILL_IDS.closeArc,
    name: "弦月·潮刃",
    description: "挥刃打出前方月牙潮刃，用短距离宽判定处理近身包围。",
    typeTag: "close_arc",
    implemented: true,
    iconSrc: "assets/sprites/skills/close_arc/icon.png",
    levelDescriptions: {
      1: "前方月牙潮刃，短距离宽判定。",
      2: "潮刃伤害提升，近身解围更稳定。",
      3: "潮刃伤害进一步提升，贴身爆发更强。",
    },
    src: "assets/sprites/skills/close_arc/skill.png",
    frameCount: 6,
    frameW: 500,
    image: null,
    frameH: 500,
    drawScale: 0.243,
    radius: 30,
    enemyBase: 37,
    enemyScale: 45,
    bossBase: 62,
    color: "#8edbff",
  },
  {
    id: SKILL_IDS.guardCounter,
    name: "镜潮·护返",
    description: "短暂起手后展开环身潮幕，预判受击时抵挡并反击近处目标。",
    typeTag: "guard_counter",
    implemented: true,
    iconSrc: "assets/sprites/skills/guard_counter/icon.png",
    levelDescriptions: {
      1: "潮幕成形后进入有限防护窗口，受击时抵挡并反击近处目标。",
      2: "反击伤害提升，防守收益更高。",
      3: "反击窗口和容错收益更稳定，但次数和持续时间仍有限。",
    },
    src: "assets/sprites/skills/guard_counter/skill.png",
    frameCount: 5,
    frameW: 540,
    image: null,
    frameH: 470,
    drawScale: 0.256,
    radius: 30,
    enemyBase: 40,
    enemyScale: 48,
    bossBase: 68,
    color: "#9be6ff",
  },
  {
    id: SKILL_IDS.dashReposition,
    name: "流步·潮闪",
    description: "踏步后短距离踏浪闪进，穿击身前敌人并以收刀斩结束。",
    typeTag: "dash_reposition",
    implemented: true,
    iconSrc: "assets/sprites/skills/dash_reposition/icon.png",
    levelDescriptions: {
      1: "短位移期间无敌，穿击身前敌人并留下收刀斩。",
      2: "位移距离和穿击伤害提升，追击更稳定。",
      3: "落点反馈增强，脱离夹击更可靠。",
    },
    src: "assets/sprites/skills/dash_reposition/skill.png",
    frameCount: 5,
    frameW: 480,
    image: null,
    frameH: 360,
    drawScale: 0.42,
    anchorX: 0.45,
    anchorY: 0.9,
    radius: 96,
    enemyBase: 28,
    enemyScale: 36,
    bossBase: 38,
    color: "#7bdcff",
  },
  {
    id: SKILL_IDS.vortexControl,
    name: "回涡·引潮",
    description: "插刃引出短时地面潮涡，轻微牵引并减速轻型敌人。",
    typeTag: "vortex_control",
    implemented: true,
    iconSrc: "assets/sprites/skills/vortex_control/icon.png",
    levelDescriptions: {
      1: "地面潮涡短时成形，轻型敌人进入涡圈后被轻微牵引和减速。",
      2: "持续时间略增，牵引、减速和持续伤害提高。",
      3: "涡圈范围和控场稳定性进一步提高，但不拉动 Boss。",
    },
    src: "assets/sprites/skills/vortex_control/skill.png",
    frameCount: 5,
    frameW: 360,
    image: null,
    frameH: 360,
    drawScale: 0.34,
    anchorX: 0.52,
    radius: 92,
    enemyBase: 18,
    enemyScale: 26,
    bossBase: 24,
    color: "#65d6ff",
  },
  {
    id: SKILL_IDS.armorBreak,
    name: "断浪·裂甲",
    description: "压缩潮线向前飞行，命中后爆裂并施加短时裂甲标记。",
    typeTag: "armor_break",
    implemented: true,
    iconSrc: "assets/sprites/skills/armor_break/icon.png",
    levelDescriptions: {
      1: "潮线命中目标后爆裂并施加短时裂甲。",
      2: "斩击伤害和裂甲持续提高。",
      3: "裂甲前置爆发收益更高，但 Boss 效果仍降低。",
    },
    src: "assets/sprites/skills/armor_break/skill.png",
    frameCount: 5,
    frameW: 360,
    image: null,
    frameH: 360,
    drawScale: 0.34,
    anchorX: 0.46,
    radius: 128,
    enemyBase: 34,
    enemyScale: 42,
    bossBase: 48,
    color: "#b7efff",
  },
  {
    id: SKILL_IDS.antiAirMulti,
    name: "雨线·穿针",
    description: "抬手定线后召来多条细潮线斜落，用于对空和远程骚扰。",
    typeTag: "anti_air_multi",
    implemented: true,
    iconSrc: "assets/sprites/skills/anti_air_multi/icon.png",
    levelDescriptions: {
      1: "多条细潮线斜落，低单段伤害但命中反馈清晰。",
      2: "潮线数量和目标覆盖稳定性提高。",
      3: "对飞行、施法或低血目标的压制更可靠。",
    },
    src: "assets/sprites/skills/anti_air_multi/skill.png",
    frameCount: 5,
    frameW: 640,
    image: null,
    frameH: 420,
    drawScale: 0.5,
    anchorX: 0.45,
    anchorY: 0.93,
    radius: 150,
    enemyBase: 18,
    enemyScale: 24,
    bossBase: 26,
    color: "#9eeaff",
  },
  {
    id: SKILL_IDS.returningBlade,
    name: "回刃·归潮",
    description: "放出潮刃后沿路径回收，去程和返程分别可命中。",
    typeTag: "returning_blade",
    implemented: true,
    iconSrc: "assets/sprites/skills/returning_blade/icon.png",
    levelDescriptions: {
      1: "潮刃飞出后返回，站位正确可获得两段命中。",
      2: "飞行距离和命中上限提高，路线收益更稳定。",
      3: "返程命中收益更高，但不自动追踪全场。",
    },
    src: "assets/sprites/skills/returning_blade/skill.png",
    frameCount: 5,
    frameW: 360,
    image: null,
    frameH: 360,
    drawScale: 0.58,
    anchorX: 0.48,
    radius: 150,
    enemyBase: 25,
    enemyScale: 34,
    bossBase: 42,
    color: "#80e2ff",
  },
  {
    id: SKILL_IDS.verticalWave,
    name: "升浪·托月",
    description: "压低重心后升起短浪柱，处理纵向目标和平台边缘贴身压力。",
    typeTag: "vertical_wave",
    implemented: true,
    iconSrc: "assets/sprites/skills/vertical_wave/icon.png",
    levelDescriptions: {
      1: "升起短浪柱或弧形上挑，轻微打断贴身小怪。",
      2: "浪柱高度和伤害提高。",
      3: "纵向覆盖更稳定，但不长期浮空连控。",
    },
    src: "assets/sprites/skills/vertical_wave/skill.png",
    frameCount: 6,
    frameW: 480,
    image: null,
    frameH: 420,
    drawScale: 0.34,
    anchorX: 0.4,
    anchorY: 0.98,
    radius: 110,
    enemyBase: 30,
    enemyScale: 38,
    bossBase: 44,
    color: "#9be8ff",
  },
];
