import { SKILL_IDS } from "../ids";
import type { Skill } from "../../types/assets";

export const SKILLS: Skill[] = [
  {
    id: SKILL_IDS.lineProjectile,
    name: "潮龙破",
    description: "向前释放一条水龙冲击，给路径上的敌人造成伤害。",
    typeTag: "line_projectile",
    implemented: true,
    iconSrc: "assets/sprites/skills/line_projectile/icon.png",
    levelDescriptions: {
      1: "向前释放水龙，造成窄长路径伤害。",
      2: "水龙伤害提升，命中反馈更稳定。",
      3: "水龙伤害进一步提升，直线压制更可靠。",
    },
    src: "assets/sprites/skills/line_projectile/skill.png",
    frameCount: 5,
    frameW: 800,
    image: null,
    frameH: 420,
    drawScale: 0.247,
    anchorX: 0.15,
    radius: 30,
    enemyBase: 34,
    enemyScale: 42,
    bossBase: 56,
    color: "#7fdfff",
  },
  {
    id: SKILL_IDS.closeArc,
    name: "打潮刃",
    description: "向前挥出大范围水之呼吸剑气，席卷路径上的敌人。",
    typeTag: "close_arc",
    implemented: true,
    iconSrc: "assets/sprites/skills/close_arc/icon.png",
    levelDescriptions: {
      1: "前方月牙水刃，短距离宽判定。",
      2: "潮刃伤害提升，近身解围更稳定。",
      3: "潮刃伤害进一步提升，贴身爆发更强。",
    },
    src: "assets/sprites/skills/close_arc/skill.png",
    frameCount: 6,
    frameW: 500,
    image: null,
    frameH: 500,
    drawScale: 0.243,
    radius: 30,
    enemyBase: 37,
    enemyScale: 45,
    bossBase: 62,
    color: "#8edbff",
  },
  {
    id: SKILL_IDS.guardCounter,
    name: "镜潮返",
    description: "展开防护水幕，受到攻击时反击身边的敌人。",
    typeTag: "guard_counter",
    implemented: true,
    iconSrc: "assets/sprites/skills/guard_counter/icon.png",
    levelDescriptions: {
      1: "展开防护水幕，受击时抵挡并反击近处目标。",
      2: "反击伤害提升，防守收益更高。",
      3: "反击伤害进一步提升，容错收益更高。",
    },
    src: "assets/sprites/skills/guard_counter/skill.png",
    frameCount: 5,
    frameW: 540,
    image: null,
    frameH: 470,
    drawScale: 0.256,
    radius: 30,
    enemyBase: 40,
    enemyScale: 48,
    bossBase: 68,
    color: "#9be6ff",
  },
  {
    id: SKILL_IDS.dashReposition,
    name: "流步·潮闪",
    description: "短距离踏浪前冲，穿过身前敌人时无敌并造成伤害，结束时向前收刀斩击。",
    typeTag: "dash_reposition",
    implemented: true,
    iconSrc: "assets/sprites/skills/dash_reposition/icon.png",
    levelDescriptions: {
      1: "前冲 92px，穿击身前敌人并短暂无敌。",
      2: "前冲距离提升至 108px，穿击伤害提高。",
      3: "前冲距离提升至 124px，追击和脱困更稳定。",
    },
    src: "assets/sprites/skills/dash_reposition/skill.png",
    frameCount: 5,
    frameW: 480,
    image: null,
    frameH: 360,
    drawScale: 0.42,
    anchorX: 0.45,
    anchorY: 0.9,
    radius: 96,
    enemyBase: 28,
    enemyScale: 36,
    bossBase: 38,
    color: "#7bdcff",
  },
  {
    id: SKILL_IDS.vortexControl,
    name: "回涡·引潮",
    description: "在地面生成短时潮涡，轻微牵引并减速小怪。",
    typeTag: "vortex_control",
    implemented: true,
    iconSrc: "assets/sprites/skills/vortex_control/icon.png",
    levelDescriptions: {
      1: "潮涡持续 54 帧，脚底进入涡圈的小怪被轻微牵引和减速。",
      2: "潮涡持续 66 帧，牵引、减速和持续伤害提高。",
      3: "潮涡持续 78 帧，涡圈范围和控场稳定性进一步提高。",
    },
    src: "assets/sprites/skills/vortex_control/skill.png",
    frameCount: 5,
    frameW: 360,
    image: null,
    frameH: 360,
    drawScale: 0.34,
    anchorX: 0.52,
    radius: 92,
    enemyBase: 18,
    enemyScale: 26,
    bossBase: 24,
    color: "#65d6ff",
  },
  {
    id: SKILL_IDS.armorBreak,
    name: "断浪·裂甲",
    description: "向前飞出压缩潮线，命中后爆裂并施加短时裂甲标记。",
    typeTag: "armor_break",
    implemented: true,
    iconSrc: "assets/sprites/skills/armor_break/icon.png",
    levelDescriptions: {
      1: "潮线命中目标后爆裂并施加短时裂甲。",
      2: "斩击伤害和裂甲持续提高。",
      3: "裂甲前置爆发收益更高，但 Boss 效果仍降低。",
    },
    src: "assets/sprites/skills/armor_break/skill.png",
    frameCount: 5,
    frameW: 360,
    image: null,
    frameH: 360,
    drawScale: 0.34,
    anchorX: 0.46,
    radius: 128,
    enemyBase: 34,
    enemyScale: 42,
    bossBase: 48,
    color: "#b7efff",
  },
  {
    id: SKILL_IDS.antiAirMulti,
    name: "雨线·穿针",
    description: "召来多条细潮线斜落，前方有敌时优先落向目标。",
    typeTag: "anti_air_multi",
    implemented: true,
    iconSrc: "assets/sprites/skills/anti_air_multi/icon.png",
    levelDescriptions: {
      1: "生成 4 条窄潮线，优先落向前方威胁目标。",
      2: "潮线增加至 5 条，目标覆盖更稳定。",
      3: "潮线增加至 6 条，对空和补刀更可靠。",
    },
    src: "assets/sprites/skills/anti_air_multi/skill.png",
    frameCount: 5,
    frameW: 640,
    image: null,
    frameH: 420,
    drawScale: 0.5,
    anchorX: 0.45,
    anchorY: 0.93,
    radius: 150,
    enemyBase: 18,
    enemyScale: 24,
    bossBase: 26,
    color: "#9eeaff",
  },
  {
    id: SKILL_IDS.returningBlade,
    name: "镜潮·返刃",
    description: "发出潮刃后沿路线回收，去程和返程分别可命中。",
    typeTag: "returning_blade",
    implemented: true,
    iconSrc: "assets/sprites/skills/returning_blade/icon.png",
    levelDescriptions: {
      1: "潮刃飞出后返回，站位正确可获得两段命中。",
      2: "飞行距离和命中上限提高。",
      3: "往返路线收益更高，但不自动追踪全场。",
    },
    src: "assets/sprites/skills/returning_blade/skill.png",
    frameCount: 5,
    frameW: 360,
    image: null,
    frameH: 360,
    drawScale: 0.58,
    anchorX: 0.48,
    radius: 150,
    enemyBase: 25,
    enemyScale: 34,
    bossBase: 42,
    color: "#80e2ff",
  },
  {
    id: SKILL_IDS.verticalWave,
    name: "升浪·托月",
    description: "自前方或脚下升起短浪柱，打断贴身和纵向目标。",
    typeTag: "vertical_wave",
    implemented: true,
    iconSrc: "assets/sprites/skills/vertical_wave/icon.png",
    levelDescriptions: {
      1: "升起短浪柱，轻微上抛或打断小怪。",
      2: "浪柱高度和伤害提高。",
      3: "纵向覆盖更稳定，但不长期浮空控场。",
    },
    src: "assets/sprites/skills/vertical_wave/skill.png",
    frameCount: 6,
    frameW: 480,
    image: null,
    frameH: 420,
    drawScale: 0.34,
    anchorX: 0.4,
    anchorY: 0.98,
    radius: 110,
    enemyBase: 30,
    enemyScale: 38,
    bossBase: 44,
    color: "#9be8ff",
  },
];
