export const MIST_BONE_CONFIG = {
  attackDuration: 48,
  attackFrameDuration: 8,
  attackReleaseFrame: 24,
  attackShotInterval: 6,
  attackMaxShots: 3,
  attackMinDistance: 130,
  attackMaxDistance: 420,
  attackCooldown: 104,
  attackCooldownPhaseReduction: 8,
  attackMinCooldown: 72,
  dartHitW: 34,
  dartHitH: 14,
  dartDrawW: 64,
  dartDrawH: 38,
  dartSpeed: 8.2,
  dartSpeedPhase: 0.35,
  dartLife: 120,
  dartDamageBase: 5,
  dartDamagePhase: 1,
  dartSpawnOffsetX: 108,
  dartSpawnYScale: 0.32,
  dartVy: 3.2,
  dartFrameDuration: 5,
  castDuration: 64,
  spawnAtFrame: 30,
  castFrameDuration: 9,
  recoveryFrames: 38,
  initialCooldown: 118,
  skillCooldown: 226,
  drawW: 176,
  drawH: 208,
  castDrawW: 228,
  castDrawH: 228,
  castBottomPadding: 0,
  preferredDistance: 196,
  closeDistance: 128,
  steeringForce: 0.04,
  retreatForce: 0.068,
  drag: 0.9,
  maxVelocity: 2.65,
  spikeWarningFrames: 28,
  spikeWarningSpriteFrames: 2,
  spikeLife: 78,
  spikeFrameDuration: 7,
  spikeHitW: 72,
  spikeHitH: 44,
  spikeDrawW: 120,
  spikeDrawH: 106,
  spikeDelayStep: 10,
  lineSpacing: 86,
  lineBaseCount: 3,
  lineMaxCount: 5,
  cageCount: 7,
  cageSpacing: 74,
  damageBase: 10,
  damagePhase: 2,
  thinFogRadiusX: 156,
  thinFogRadiusY: 52,
  thinFogLife: 210,
  thinFogMoveScale: 0.78,
  burialFogRadiusX: 330,
  burialFogRadiusY: 210,
  burialFogLife: 126,
  chaseMinPhase: 3,
  chaseFrames: 26,
  chaseSpeed: 8,
  chaseRecoveryFrames: 38,
  supportMinPhase: 4,
} as const;

const FANG_GALE_PHASE_ONE_CHASE_COOLDOWN = 72;
const FANG_GALE_PHASE_TWO_CHASE_COOLDOWN = 64;
const FANG_GALE_PHASE_THREE_CHASE_COOLDOWN = 56;
const FANG_GALE_PHASE_FOUR_CHASE_COOLDOWN = 48;

export const FANG_GALE_CONFIG = {
  normalSkillWeights: [
    { dash: 1, wave: 0 },
    { dash: 0.56, wave: 0.44 },
    { dash: 0.34, wave: 0.66 },
  ],
  awakenedSkillWeights: [
    { dash: 0.88, wave: 0, storm: 0.12 },
    { dash: 0.56, wave: 0.22, storm: 0.22 },
    { dash: 0.34, wave: 0.32, storm: 0.34 },
    { dash: 0.2, wave: 0.2, storm: 0.6 },
  ],
  castDuration: 42,
  stormCastDuration: 54,
  retreatFrames: 18,
  retreatSpeed: 3.2,
  recoveryFrames: 30,
  stormRecoveryFrames: 66,
  chainWindupFrames: 24,
  chainWindupPhaseReduction: 2,
  chainWindupMinFrames: 18,
  initialCooldown: 104,
  postRecoveryCooldowns: [
    FANG_GALE_PHASE_ONE_CHASE_COOLDOWN,
    FANG_GALE_PHASE_TWO_CHASE_COOLDOWN,
    FANG_GALE_PHASE_THREE_CHASE_COOLDOWN,
    FANG_GALE_PHASE_FOUR_CHASE_COOLDOWN,
  ],
  drawW: 184,
  drawH: 218,
  castDrawW: 232,
  castDrawH: 232,
  castBottomPadding: 24,
  steeringForce: 0.062,
  drag: 0.88,
  maxVelocity: 4.1,
  dashFrames: 30,
  stormDashFrames: 36,
  waveComboPhase: 3,
  waveDashCount: 2,
  stormDashCount: 3,
  dashSpeed: 10.8,
  stormDashSpeed: 12.2,
  stormFinalDashSpeedMultiplier: 1.2,
  dashHitW: 160,
  dashHitH: 120,
  dashDamageBase: 11,
  dashDamagePhase: 2,
  waveWarningFrames: 12,
  waveWarningSpriteFrames: 2,
  waveLife: 118,
  waveSpeed: 7.8,
  waveHitW: 64,
  waveHitH: 48,
  waveDrawW: 132,
  waveDrawH: 116,
  waveFrameDuration: 6,
  waveDamageBase: 9,
  waveDamagePhase: 2,
} as const;
