const SECONDS_PER_MINUTE = 60;
const FRAMES_PER_SECOND = 60;

export const BASIC_ATTACK = {
  damage: 16,
  reach: 64,
  frames: 18,
  color: "#6be0ff",
  yOffset: 28,
  height: 48,
} as const;

export const FALL_ATTACK = {
  startVelocity: 5,
  diveVelocity: 7,
  maxVelocity: 12,
  horizontalDrag: 0.9,
  radius: 92,
  height: 78,
  damageMultiplier: 1.65,
  bossDamageMultiplier: 1.35,
  enemyHitCooldown: 12,
  bossHitCooldown: 10,
  landingInvincibleFrames: 8,
  recoveryFrames: 10,
  color: "#8feaff",
  impactBurstPower: 2.2,
} as const;

export const PLAYER_DEFAULTS = {
  x: 148,
  yOffsetFromGround: 94,
  w: 44,
  h: 94,
  speed: 4,
  jump: 14,
  facing: 1,
  maxHp: 100,
  baseAttack: BASIC_ATTACK.damage,
  maxSkillEnergy: 90,
  maxSkillCharges: 3,
  maxUltimateEnergy: 100,
} as const;

export const PLAYER_LIMITS = {
  maxHp: 100,
  maxSkillEnergy: 90,
  maxSkillCharges: 3,
  maxUltimateEnergy: 100,
  attackBonusCap: 24,
} as const;

export const PLAYER_COMBAT = {
  skillBurstLife: 40,
  skillBurstYOffset: 2,
  skillScaleIn: 0.92,
  skillScaleOut: 1.08,
  skillEnemyBurstPower: 1.5,
  skillBossBurstPower: 2.2,
  attackEnemyBurstPower: 1.0,
  attackBossBurstPower: 1.4,
  enemyHitCooldown: 12,
  bossHitCooldown: 10,
  bossRadiusPadding: 40,
  bossMinDamageRatio: 0.2,
  attackBonusScale: 0.025,
  enemyKillScore: 12,
  bossKillScore: 220,
  enemyEnergyGain: 10,
  bossEnergyGain: 60,
  enemyUltimateEnergyGain: 8 / 3,
  bossUltimateEnergyGain: 40,
  ultimateRadius: 360,
  ultimateCastFrames: 24,
  ultimateCastFrameDuration: 4,
  ultimateStartupInvincibleFrames: 8,
  ultimateEffectFrameDuration: 8,
  ultimateEffectLife: 96,
  ultimateEffectSpawnRatio: 0.45,
  ultimateDrawScale: 0.42,
  ultimateEffectDrawScale: 0.68,
  ultimateEffectYOffset: 78,
  ultimateTrailLife: 18,
  ultimateTrailSpawnInterval: 3,
  ultimateAfterimageLife: 12,
  skillCastEnergyCost: 30,
  skillChargeResetDelay: 45,
  hurtInvincibleFrames: 28,
  hurtKnockbackX: 7,
  hurtKnockbackY: -5,
  attackEnemyHitCooldown: 8,
  attackBossHitCooldown: 7,
  attackKillScore: 10,
  attackHitY: 20,
  attackKillY: 24,
  bossHitXRatio: 0.4,
  bossHitY: 30,
  blinkInterval: 3,
  movementIdleThreshold: 1.1,
  groundDrag: 0.72,
  platformEdgePadding: 8,
  platformLandingTolerance: 2,
  effects: {
    skillEnemyBurstColor: "#9beeff",
    skillBossSlashColor: "#9beeff",
    skillBossBurstColor: "#c8f4ff",
    hurtSlashColor: "#ff4e73",
    attackEnemyBurstColor: "#8ee6ff",
    attackKillSlashColor: "#ff915d",
    attackBossBurstColor: "#b4efff",
    bossKillSlashColor: "#ffc96b",
  },
  tones: {
    attackStart: { frequency: 320, duration: 0.07, volume: 0.05 },
    skillCastPrimary: { frequency: 620, duration: 0.11, volume: 0.06 },
    skillCastSecondary: { frequency: 860, duration: 0.09, volume: 0.05 },
    hurt: { frequency: 120, duration: 0.12, volume: 0.05 },
    jump: { frequency: 260, duration: 0.05, volume: 0.04 },
    attackHit: { baseFrequency: 430, randomVariance: 60, duration: 0.04, volume: 0.025 },
    bossHit: { frequency: 180, duration: 0.06, volume: 0.05 },
    bossKill: { frequency: 700, duration: 0.12, volume: 0.06 },
  },
} as const;

export const MOON_TIDE_ULTIMATE = {
  1: {
    durationFrames: 6 * FRAMES_PER_SECOND,
    moveSpeedMultiplier: 1.12,
    jumpMultiplier: 1.08,
    attackFrameMultiplier: 0.9,
    damageMultiplier: 1.15,
    afterimageChance: 0.35,
    afterimageDamageMultiplier: 0.22,
    afterimageCount: 1,
    afterimageBurstPower: 0.7,
  },
  2: {
    durationFrames: 7.5 * FRAMES_PER_SECOND,
    moveSpeedMultiplier: 1.18,
    jumpMultiplier: 1.12,
    attackFrameMultiplier: 0.82,
    damageMultiplier: 1.25,
    afterimageChance: 0.6,
    afterimageDamageMultiplier: 0.28,
    afterimageCount: 1,
    afterimageBurstPower: 0.9,
  },
  3: {
    durationFrames: 9 * FRAMES_PER_SECOND,
    moveSpeedMultiplier: 1.25,
    jumpMultiplier: 1.16,
    attackFrameMultiplier: 0.76,
    damageMultiplier: 1.35,
    afterimageChance: 1,
    afterimageDamageMultiplier: 0.35,
    afterimageCount: 2,
    afterimageBurstPower: 1.15,
  },
} as const;

export const PLAYER_DRAW = {
  yOffset: 2,
  fallbackSkillDrawH: 150,
  skillAnimFps: 12,
} as const;

export const ENEMY_CONFIG = {
  spawnSideChance: 0.5,
  spawnOffsetRight: 20,
  spawnOffsetLeft: -40,
  yOffsetFromGround: 75,
  w: 55,
  h: 75,
  collisionScaleX: 0.42,
  collisionScaleY: 0.78,
  baseSpeed: 0.72,
  randomSpeed: 1.08,
  speedScaleByElapsed: 1 / SECONDS_PER_MINUTE,
  maxDamage: 20,
  baseDamage: 3,
  damageScaleByElapsed: 0.1,
  baseHp: 16,
  hpScaleByElapsed: 0.3,
  maxAbsVelocity: 3.2,
  steeringForce: 0.03,
  despawnMargin: 120,
  animSeedMax: 60,
  animSpeed: 7,
} as const;

export const BOSS_CONFIG = {
  spawnOffsetX: 140,
  yOffsetFromGround: 188,
  w: 104,
  h: 188,
  entryVelocityX: -2.6,
  targetXOffset: 170,
  baseHp: 460,
  hpScaleByElapsed: 2.2,
  entryAiDelay: 32,
  phaseTwoThreshold: 0.66,
  phaseThreeThreshold: 0.33,
  baseSteeringForce: 0.08,
  phaseSteeringForce: 0.02,
  drag: 0.94,
  baseMaxVelocity: 4.8,
  projectileChance: 0.55,
  projectileYOffset: 58,
  projectileYOffsetStep: 10,
  projectileW: 12,
  projectileH: 8,
  projectileBaseSpeed: 5.2,
  projectileSpeedStep: 0.6,
  projectileLife: 90,
  projectileBaseDamage: 8,
  summonExtraEnemyPhase: 3,
  aiBaseCooldown: 100,
  aiPhaseReduction: 14,
  jumpChancePerPhase: 0.03,
  jumpVelocityBase: 6,
  jumpCooldown: 34,
  touchDamageBase: 12,
  touchDamagePhase: 2,
  animSeedMax: 80,
  baseAnimSpeed: 9,
  bodyDrawScale: 2,
  drawOffsetX: 0,
  drawOffsetY: 0,
  drawW: 176,
  drawH: 208,
  tones: {
    spawnPrimary: { frequency: 120, duration: 0.2, volume: 0.06 },
    spawnSecondary: { frequency: 90, duration: 0.25, volume: 0.05 },
    projectile: { frequency: 190, duration: 0.08, volume: 0.05 },
    summon: { frequency: 100, duration: 0.09, volume: 0.045 },
  },
} as const;

export const PROJECTILE_CONFIG = {
  despawnMargin: 24,
  primaryColor: "#ff6e93",
  highlightColor: "#ffe2ef",
  highlightOffset: 2,
  highlightSize: 3,
} as const;

export const PARTICLE_CONFIG = {
  slashCount: 12,
  slashVelocity: 7,
  slashLifeBase: 20,
  slashLifeVariance: 10,
  velocityFade: 0.96,
  sizeFade: 0.97,
  defaultSize: 3,
  slashDefaultSpread: 10,
} as const;

export const HIT_BURST_CONFIG = {
  baseLife: 10,
  lifeScale: 8,
  baseRadius: 8,
  radiusScale: 6,
  baseGrow: 1.8,
  growScale: 1.2,
  baseSparks: 8,
  sparkScale: 8,
  sparkAngleJitter: 0.25,
  sparkDistBase: 1,
  sparkDistVariance: 5,
  sparkSpeedBase: 1.2,
  sparkSpeedVariance: 2.4,
  sparkSpeedPowerScale: 0.5,
  sparkSizeBase: 1.4,
  sparkSizeVariance: 1.8,
  minInnerRadius: 2,
} as const;
