export const BASIC_ATTACK = {
  damage: 16,
  reach: 64,
  frames: 16,
  color: "#6be0ff",
  yOffset: 8,
  height: 38,
} as const;

export const PLAYER_DEFAULTS = {
  x: 140,
  yOffsetFromGround: 56,
  w: 34,
  h: 56,
  speed: 4,
  jump: 14,
  facing: 1,
  hp: 100,
  skillEnergy: 100,
  skillCharges: 3,
} as const;

export const PLAYER_LIMITS = {
  maxHp: 100,
  maxSkillEnergy: 100,
  maxSkillCharges: 3,
  attackBonusCap: 24,
} as const;

export const PLAYER_COMBAT = {
  skillTimerFrames: 24,
  skillBurstLife: 40,
  skillBurstYOffset: 2,
  skillBurstWidth: 400,
  skillBurstHeight: 300,
  skillScaleIn: 0.92,
  skillScaleOut: 1.08,
  enemyHitCooldown: 12,
  bossHitCooldown: 10,
  bossRadiusPadding: 40,
  bossMinDamageRatio: 0.2,
  attackBonusScale: 0.025,
  enemyKillScore: 12,
  bossKillScore: 220,
  enemyEnergyGain: 35,
  bossEnergyGain: 100,
  skillEnergySpendClamp: 99,
  skillChargeResetDelay: 45,
  hurtInvincibleFrames: 28,
  hurtKnockbackX: 7,
  hurtKnockbackY: -5,
  attackEnemyHitCooldown: 8,
  attackBossHitCooldown: 7,
  attackKillScore: 10,
  attackHitY: 20,
  attackKillY: 24,
  bossHitXRatio: 0.4,
  bossHitY: 30,
  blinkInterval: 3,
  movementIdleThreshold: 1.1,
} as const;

export const PLAYER_DRAW = {
  idle: { w: 145, h: 101 },
  action: { w: 132, h: 92 },
  yOffset: 2,
  fallbackSkillFrameH: 496,
  fallbackSkillDrawH: 150,
  fallbackAnimSpeed: {
    attack: 3,
    run: 5,
    jump: 7,
    idle: 8,
  },
} as const;

export const ENEMY_CONFIG = {
  spawnSideChance: 0.5,
  spawnOffsetRight: 20,
  spawnOffsetLeft: -40,
  yOffsetFromGround: 48,
  w: 30,
  h: 48,
  baseSpeed: 0.72,
  randomSpeed: 1.08,
  speedScaleByElapsed: 1 / 60,
  maxDamage: 20,
  baseDamage: 3,
  damageScaleByElapsed: 0.1,
  baseHp: 16,
  hpScaleByElapsed: 0.3,
  maxAbsVelocity: 3.2,
  steeringForce: 0.03,
  despawnMargin: 120,
  animSeedMax: 60,
  animSpeed: 7,
} as const;

export const BOSS_CONFIG = {
  spawnOffsetX: 140,
  yOffsetFromGround: 92,
  w: 72,
  h: 92,
  entryVelocityX: -2.6,
  targetXOffset: 170,
  baseHp: 460,
  hpScaleByElapsed: 2.2,
  entryAiDelay: 32,
  phaseTwoThreshold: 0.66,
  phaseThreeThreshold: 0.33,
  baseSteeringForce: 0.08,
  phaseSteeringForce: 0.02,
  drag: 0.94,
  baseMaxVelocity: 4.8,
  projectileChance: 0.55,
  projectileYOffset: 16,
  projectileYOffsetStep: 10,
  projectileW: 12,
  projectileH: 8,
  projectileBaseSpeed: 5.2,
  projectileSpeedStep: 0.6,
  projectileLife: 90,
  projectileBaseDamage: 8,
  summonExtraEnemyPhase: 3,
  aiBaseCooldown: 100,
  aiPhaseReduction: 14,
  jumpChancePerPhase: 0.03,
  jumpVelocityBase: 6,
  jumpCooldown: 34,
  touchDamageBase: 12,
  touchDamagePhase: 2,
  animSeedMax: 80,
  baseAnimSpeed: 9,
  drawOffsetX: 52,
  drawOffsetY: 108,
  drawW: 176,
  drawH: 208,
} as const;

export const PROJECTILE_CONFIG = {
  despawnMargin: 24,
  primaryColor: "#ff6e93",
  highlightColor: "#ffe2ef",
  highlightOffset: 2,
  highlightSize: 3,
} as const;

export const PARTICLE_CONFIG = {
  slashCount: 12,
  slashVelocity: 7,
  slashLifeBase: 20,
  slashLifeVariance: 10,
  velocityFade: 0.96,
  sizeFade: 0.97,
  defaultSize: 3,
} as const;

export const HIT_BURST_CONFIG = {
  baseLife: 10,
  lifeScale: 8,
  baseRadius: 8,
  radiusScale: 6,
  baseGrow: 1.8,
  growScale: 1.2,
  baseSparks: 8,
  sparkScale: 8,
  sparkAngleJitter: 0.25,
  sparkDistBase: 1,
  sparkDistVariance: 5,
  sparkSpeedBase: 1.2,
  sparkSpeedVariance: 2.4,
  sparkSpeedPowerScale: 0.5,
  sparkSizeBase: 1.4,
  sparkSizeVariance: 1.8,
  minInnerRadius: 2,
} as const;
