const SECONDS_PER_MINUTE = 60;

export const BASIC_ATTACK = {
  damage: 16,
  reach: 64,
  frames: 18,
  color: "#6be0ff",
  yOffset: 8,
  height: 38,
} as const;

export const PLAYER_DEFAULTS = {
  x: 140,
  yOffsetFromGround: 56,
  w: 34,
  h: 56,
  speed: 4,
  jump: 14,
  facing: 1,
  maxHp: 100,
  baseAttack: BASIC_ATTACK.damage,
  maxSkillEnergy: 100,
  maxSkillCharges: 3,
} as const;

export const PLAYER_LIMITS = {
  maxHp: 100,
  maxSkillEnergy: 100,
  maxSkillCharges: 3,
  attackBonusCap: 24,
} as const;

export const PLAYER_COMBAT = {
  skillBurstLife: 40,
  skillBurstYOffset: 2,
  skillScaleIn: 0.92,
  skillScaleOut: 1.08,
  skillEnemyBurstPower: 1.5,
  skillBossBurstPower: 2.2,
  attackEnemyBurstPower: 1.0,
  attackBossBurstPower: 1.4,
  enemyHitCooldown: 12,
  bossHitCooldown: 10,
  bossRadiusPadding: 40,
  bossMinDamageRatio: 0.2,
  attackBonusScale: 0.025,
  enemyKillScore: 12,
  bossKillScore: 220,
  enemyEnergyGain: 35,
  bossEnergyGain: 100,
  skillEnergySpendClamp: 99,
  skillChargeResetDelay: 45,
  hurtInvincibleFrames: 28,
  hurtKnockbackX: 7,
  hurtKnockbackY: -5,
  attackEnemyHitCooldown: 8,
  attackBossHitCooldown: 7,
  attackKillScore: 10,
  attackHitY: 20,
  attackKillY: 24,
  bossHitXRatio: 0.4,
  bossHitY: 30,
  blinkInterval: 3,
  movementIdleThreshold: 1.1,
  groundDrag: 0.72,
  platformEdgePadding: 8,
  platformLandingTolerance: 2,
  effects: {
    skillEnemyBurstColor: "#9beeff",
    skillBossSlashColor: "#9beeff",
    skillBossBurstColor: "#c8f4ff",
    hurtSlashColor: "#ff4e73",
    attackEnemyBurstColor: "#8ee6ff",
    attackKillSlashColor: "#ff915d",
    attackBossBurstColor: "#b4efff",
    bossKillSlashColor: "#ffc96b",
  },
  tones: {
    attackStart: { frequency: 320, duration: 0.07, volume: 0.05 },
    skillCastPrimary: { frequency: 620, duration: 0.11, volume: 0.06 },
    skillCastSecondary: { frequency: 860, duration: 0.09, volume: 0.05 },
    hurt: { frequency: 120, duration: 0.12, volume: 0.05 },
    jump: { frequency: 260, duration: 0.05, volume: 0.04 },
    attackHit: { baseFrequency: 430, randomVariance: 60, duration: 0.04, volume: 0.025 },
    bossHit: { frequency: 180, duration: 0.06, volume: 0.05 },
    bossKill: { frequency: 700, duration: 0.12, volume: 0.06 },
  },
} as const;

export const PLAYER_DRAW = {
  idle: { w: 145, h: 101 },
  action: { w: 132, h: 92 },
  attack: { w: 146, h: 146, bottomPad: 9 },
  yOffset: 2,
  fallbackSkillFrameH: 496,
  fallbackSkillDrawH: 150,
  fallbackSkillFrameCount: 6,
  skillAnimFps: 12,
  fallbackAnimSpeed: {
    attack: 3,
    run: 5,
    jump: 7,
    idle: 8,
  },
} as const;

export const ENEMY_CONFIG = {
  spawnSideChance: 0.5,
  spawnOffsetRight: 20,
  spawnOffsetLeft: -40,
  yOffsetFromGround: 48,
  w: 30,
  h: 48,
  baseSpeed: 0.72,
  randomSpeed: 1.08,
  speedScaleByElapsed: 1 / SECONDS_PER_MINUTE,
  maxDamage: 20,
  baseDamage: 3,
  damageScaleByElapsed: 0.1,
  baseHp: 16,
  hpScaleByElapsed: 0.3,
  maxAbsVelocity: 3.2,
  steeringForce: 0.03,
  despawnMargin: 120,
  animSeedMax: 60,
  animSpeed: 7,
} as const;

export const BOSS_CONFIG = {
  spawnOffsetX: 140,
  yOffsetFromGround: 92,
  w: 72,
  h: 92,
  entryVelocityX: -2.6,
  targetXOffset: 170,
  baseHp: 460,
  hpScaleByElapsed: 2.2,
  entryAiDelay: 32,
  phaseTwoThreshold: 0.66,
  phaseThreeThreshold: 0.33,
  baseSteeringForce: 0.08,
  phaseSteeringForce: 0.02,
  drag: 0.94,
  baseMaxVelocity: 4.8,
  projectileChance: 0.55,
  projectileYOffset: 16,
  projectileYOffsetStep: 10,
  projectileW: 12,
  projectileH: 8,
  projectileBaseSpeed: 5.2,
  projectileSpeedStep: 0.6,
  projectileLife: 90,
  projectileBaseDamage: 8,
  summonExtraEnemyPhase: 3,
  aiBaseCooldown: 100,
  aiPhaseReduction: 14,
  jumpChancePerPhase: 0.03,
  jumpVelocityBase: 6,
  jumpCooldown: 34,
  touchDamageBase: 12,
  touchDamagePhase: 2,
  animSeedMax: 80,
  baseAnimSpeed: 9,
  drawOffsetX: 52,
  drawOffsetY: 108,
  drawW: 176,
  drawH: 208,
  tones: {
    spawnPrimary: { frequency: 120, duration: 0.2, volume: 0.06 },
    spawnSecondary: { frequency: 90, duration: 0.25, volume: 0.05 },
    projectile: { frequency: 190, duration: 0.08, volume: 0.05 },
    summon: { frequency: 100, duration: 0.09, volume: 0.045 },
  },
} as const;

export const PROJECTILE_CONFIG = {
  despawnMargin: 24,
  primaryColor: "#ff6e93",
  highlightColor: "#ffe2ef",
  highlightOffset: 2,
  highlightSize: 3,
} as const;

export const PARTICLE_CONFIG = {
  slashCount: 12,
  slashVelocity: 7,
  slashLifeBase: 20,
  slashLifeVariance: 10,
  velocityFade: 0.96,
  sizeFade: 0.97,
  defaultSize: 3,
  slashDefaultSpread: 10,
} as const;

export const HIT_BURST_CONFIG = {
  baseLife: 10,
  lifeScale: 8,
  baseRadius: 8,
  radiusScale: 6,
  baseGrow: 1.8,
  growScale: 1.2,
  baseSparks: 8,
  sparkScale: 8,
  sparkAngleJitter: 0.25,
  sparkDistBase: 1,
  sparkDistVariance: 5,
  sparkSpeedBase: 1.2,
  sparkSpeedVariance: 2.4,
  sparkSpeedPowerScale: 0.5,
  sparkSizeBase: 1.4,
  sparkSizeVariance: 1.8,
  minInnerRadius: 2,
} as const;
