export const RESIDUAL_SPIRIT_CONFIG = {
  maxStored: 60,
  healCost: 20,
  healRatio: 0.15,
  healChannelSeconds: 0.6,
  healCompletionVisualSeconds: 0.18,
  dropByTier: {
    1: 3,
    2: 4,
    3: 5,
    4: 5,
  },
  eliteDrop: 8,
  splitlingDrop: 1,
  pickup: {
    collisionSize: 24,
    lifetimeSeconds: 12,
    bobAmplitude: 3,
    bobSpeed: 4,
    auraPadding: 6,
    auraAlpha: 0.3,
    pickupBurstPower: 1.4,
    pickupTone: {
      frequency: 620,
      duration: 0.09,
      volume: 0.05,
    },
  },
  pickupFlight: {
    durationSeconds: 0.36,
    maxActive: 12,
    baseParticleCount: 3,
    amountPerExtraParticle: 2,
    maxParticleCount: 7,
    trailProgressGap: 0.045,
    arcHeightRatio: 0.16,
    maxArcHeight: 88,
    swayRatio: 0.04,
    maxSway: 24,
    coreSize: 4,
    trailSizeStep: 0.55,
  },
} as const;
