import type {
  EquipmentFamily,
  EquipmentItemId,
  EquipmentItemState,
  EquipmentSlot,
} from "../types/game-state";

export const EQUIPMENT_FAMILY_LABELS: Record<EquipmentFamily, string> = {
  flow: "流水",
  burst: "破势",
  shadowstep: "影步",
  hunt: "狩猎",
  risk: "残心",
  tempo: "节奏",
};

export const EQUIPMENT_ITEMS: Record<EquipmentItemId, EquipmentItemState> = {
  flow_blade: {
    id: "flow_blade",
    name: "流水刃",
    slot: "blade",
    family: "flow",
    tier: "common",
    summary: "普攻命中 4 次后，下一次技能伤害提高。",
    uiTags: ["刃器", "普通", "普攻蓄势"],
  },
  flow_garb: {
    id: "flow_garb",
    name: "涟波衣",
    slot: "garb",
    family: "flow",
    tier: "common",
    summary: "释放技能后，短时间内移动速度提高。",
    uiTags: ["衣装", "普通", "释放机动"],
  },
  flow_talisman: {
    id: "flow_talisman",
    name: "潮声符",
    slot: "talisman",
    family: "flow",
    tier: "common",
    summary: "技能命中 2 个以上目标时，返还少量技能能量。",
    uiTags: ["饰符", "普通", "命中返能"],
  },
  burst_blade: {
    id: "burst_blade",
    name: "破月刃",
    slot: "blade",
    family: "burst",
    tier: "common",
    summary: "Boss 生命低于 35% 时，对 Boss 伤害提高。",
    uiTags: ["刃器", "普通", "Boss 斩杀"],
  },
  burst_garb: {
    id: "burst_garb",
    name: "断月衣",
    slot: "garb",
    family: "burst",
    tier: "common",
    summary: "每场 Boss 战第一次受到致命伤害时，保留 1 点生命并获得短暂无敌。",
    uiTags: ["衣装", "普通", "Boss 保命"],
  },
  burst_talisman: {
    id: "burst_talisman",
    name: "燃魂符",
    slot: "talisman",
    family: "burst",
    tier: "common",
    summary: "对 Boss 造成伤害时，短冷却额外获得少量大招能量。",
    uiTags: ["饰符", "普通", "大招循环"],
  },
  shadowstep_blade: {
    id: "shadowstep_blade",
    name: "流影刃",
    slot: "blade",
    family: "shadowstep",
    tier: "common",
    summary: "连续移动一段距离后，下一次普攻范围扩大并略微增伤。",
    uiTags: ["刃器", "普通", "移动影斩"],
  },
  shadowstep_garb: {
    id: "shadowstep_garb",
    name: "踏影衣",
    slot: "garb",
    family: "shadowstep",
    tier: "common",
    summary: "连续移动时，受到伤害和击退降低；停止移动后快速消失。",
    uiTags: ["衣装", "普通", "移动容错"],
  },
  shadowstep_talisman: {
    id: "shadowstep_talisman",
    name: "掠影符",
    slot: "talisman",
    family: "shadowstep",
    tier: "common",
    summary: "从敌人附近经过后，短冷却获得少量技能能量。",
    uiTags: ["饰符", "普通", "穿梭返能"],
  },
  hunt_blade: {
    id: "hunt_blade",
    name: "狩牙刃",
    slot: "blade",
    family: "hunt",
    tier: "common",
    summary: "短时间内连续击杀小怪后，下一次普攻范围扩大。",
    uiTags: ["刃器", "普通", "连杀强化"],
  },
  hunt_garb: {
    id: "hunt_garb",
    name: "逐猎衣",
    slot: "garb",
    family: "hunt",
    tier: "common",
    summary: "击杀小怪后，短时间内移动速度提高。",
    uiTags: ["衣装", "普通", "击杀机动"],
  },
  hunt_talisman: {
    id: "hunt_talisman",
    name: "连珠符",
    slot: "talisman",
    family: "hunt",
    tier: "common",
    summary: "短时间内连续击杀 3 个小怪后，获得技能能量。",
    uiTags: ["饰符", "普通", "连杀回能"],
  },
  risk_blade: {
    id: "risk_blade",
    name: "残心刃",
    slot: "blade",
    family: "risk",
    tier: "common",
    summary: "生命低于 35% 时，普攻伤害提高。",
    uiTags: ["刃器", "普通", "低血反击"],
  },
  risk_garb: {
    id: "risk_garb",
    name: "赤纹衣",
    slot: "garb",
    family: "risk",
    tier: "common",
    summary: "生命低于 35% 时，受到伤害降低。",
    uiTags: ["衣装", "普通", "低血容错"],
  },
  risk_talisman: {
    id: "risk_talisman",
    name: "返魂符",
    slot: "talisman",
    family: "risk",
    tier: "common",
    summary: "每幕首次生命低于 35% 时，获得技能能量。",
    uiTags: ["饰符", "普通", "濒死资源"],
  },
  tempo_blade: {
    id: "tempo_blade",
    name: "疾奏刃",
    slot: "blade",
    family: "tempo",
    tier: "common",
    summary: "普攻动作更快，但单次普攻伤害略低。",
    uiTags: ["刃器", "普通", "高频普攻"],
  },
  tempo_garb: {
    id: "tempo_garb",
    name: "迅风衣",
    slot: "garb",
    family: "tempo",
    tier: "common",
    summary: "受伤后的击退略微降低，更容易回到战斗节奏。",
    uiTags: ["衣装", "普通", "抗击退"],
  },
  tempo_talisman: {
    id: "tempo_talisman",
    name: "鸣拍符",
    slot: "talisman",
    family: "tempo",
    tier: "common",
    summary: "技能消耗降低至 24，但大招能量获取略微降低。",
    uiTags: ["饰符", "普通", "低耗技能"],
  },
};

export const EQUIPMENT_CHOICE_IDS: EquipmentItemId[] = [
  "flow_blade",
  "flow_garb",
  "flow_talisman",
  "burst_blade",
  "burst_garb",
  "burst_talisman",
  "shadowstep_blade",
  "shadowstep_garb",
  "shadowstep_talisman",
  "hunt_blade",
  "hunt_garb",
  "hunt_talisman",
  "risk_blade",
  "risk_garb",
  "risk_talisman",
  "tempo_blade",
  "tempo_garb",
  "tempo_talisman",
];

export const EQUIPMENT_IDS_BY_SLOT: Record<EquipmentSlot, EquipmentItemId[]> = {
  blade: ["flow_blade", "burst_blade", "shadowstep_blade", "hunt_blade", "risk_blade", "tempo_blade"],
  garb: ["flow_garb", "burst_garb", "shadowstep_garb", "hunt_garb", "risk_garb", "tempo_garb"],
  talisman: [
    "flow_talisman",
    "burst_talisman",
    "shadowstep_talisman",
    "hunt_talisman",
    "risk_talisman",
    "tempo_talisman",
  ],
};
